### ISSUE TITLE
delta flag has not set back to false after re-index

### ISSUE THREAD

**Issue by praveenggg** [pat/ts-delayed-delta#50]
Hi Pat,
In our Project, there are 30,000 records in a table.

Suppose we are updating some columns in this table for 9000 existing records and running delta index.
so all these 9000 records have been set delta as true for indexing.

As you are saying in this case https://github.com/pat/ts-delayed-delta/issues/37, delta will not set to false after re-indexing.(Actullay this re-indexing is taking 30 min), so after re-indexing, if user creates a new record in this table, sphinx will rotate all 9001 records instead of 1 record.(Again re-index will take 30 min instead of milliseconds)
can you help me on this issue.

**Comment by pat** [comment]
Hi Praveen

When the _delta_ index is processed, you are correct, the delta flag is not changed, because it's an indication of whether the changes for that record are in the _core_ index (and that's not the case until processing of all indices occurs). Otherwise, you'd have the initial delta data forgotten when the next delta index processing happens.

When the _core_ index is processed, the delta flag is reset to false for all records. In versions prior to v3.1.0, this happened before the core index processing started. Then the behaviour was changed to have this happen _after_ the core index was processed, but has recently been reverted to be before, as that's a better way to ensure all data is as up-to-date as possible (though neither approach is quite perfect). This is discussed further in the Thinking Sphinx issue [958](https://github.com/pat/thinking-sphinx/issues/958).

Does that information help?

**Comment by praveenggg** [comment]
ok..
i will ask about this in sphinx forum.
Thanks for your help..
